### ISSUE TITLE
Performance much better than the paper says

### ISSUE THREAD

**Issue by jellllly420** [allenai/reclip#6]
Thank you for sharing your great work.

I have cloned this repo to Google Drive and run the experiments by executing `python main.py --input_file /mypath/reclip/dataset/reclip_data/refcoco*.jsonl --image_root /mypath/reclip/dataset/train2014/ --method parse --box_method_aggregator sum --clip_model RN50x16,ViT-B/32 --box_representation_method crop,blur --cache_path /mypath/reclip/cache/ --output_file /mypath/reclip/output/refcoco*.txt` in colab. However, I found that the results are all 1%-9% higher than those in the Table 2  of the paper. 

My accs are as below:
- refcocog val 67.913 test 67.069 
- refcoco+ val 52.082 testA 51.659 testB 52.015
- refcoco val 50.526 testA 47.110 testB 54.877

I wonder why this happened, Thanks.

**Comment by jellllly420** [comment]
friendly ping @sanjayss34

**Comment by taotaotao0412** [comment]
emmm, refcoco*.jsonl mean that use ground truth as bbox proposal, However, table 2 is the result of does not take ground truth BBOX as the bbox proposal. @jellllly420.

**Comment by sanjayss34** [comment]
Sorry for the delay! As @taotaotao0412 said, since you have not specified `--detector_file` in your command, the ground-truth bounding boxes have been used as proposals. Table 2 reports results using bounding boxes predicted by an object detector. The results that you have seem to match the corresponding ones in Tables 7 and 8 (in the appendix), which include results with ground-truth proposals. Please see the README for more information about how to construct the command and access detected bounding boxes, etc.

**Comment by jellllly420** [comment]
> emmm, refcoco*.jsonl mean that use ground truth as bbox proposal, However, table 2 is the result of does not take ground truth BBOX as the bbox proposal. @jellllly420.

Thanks for your reply!

**Comment by jellllly420** [comment]
> Sorry for the delay! As @taotaotao0412 said, since you have not specified `--detector_file` in your command, the ground-truth bounding boxes have been used as proposals. Table 2 reports results using bounding boxes predicted by an object detector. The results that you have seem to match the corresponding ones in Tables 7 and 8 (in the appendix), which include results with ground-truth proposals. Please see the README for more information about how to construct the command and access detected bounding boxes, etc.

Thanks for your reply and thanks again for sharing your work!
